package main.java.hw.servers.handlers.enums;

public enum Endpoint {
    GET_TASKS, GET_TASKBYID, POST_TASK, DELETE_TASK,
    GET_SUBTASKS, GET_SUBTASKBYID, POST_SUBTASK, DELETE_SUBTASK,
    GET_EPICS,GET_EPICBYID,POST_EPIC,DELETE_EPIC, GET_EPICSUBTASKS,
    UNKNOWN
}

